// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDREWFQLkwiwRfsGjp8ZgHaGch46hdmxV8',
    appId: '1:247476803253:web:6a4f07d81f5076077490fc',
    messagingSenderId: '247476803253',
    projectId: 'linkup-55edf',
    authDomain: 'linkup-55edf.firebaseapp.com',
    databaseURL: 'https://linkup-55edf-default-rtdb.firebaseio.com/',
    storageBucket: 'linkup-55edf.firebasestorage.app',
    measurementId: 'G-SXPYFBFWSP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIRmLxbkEVhu9CLatxe6t78LuA8TFkks8',
    appId: '1:247476803253:android:9734b9b422543cf77490fc',
    messagingSenderId: '247476803253',
    projectId: 'linkup-55edf',
    databaseURL: 'https://linkup-55edf-default-rtdb.firebaseio.com/',
    storageBucket: 'linkup-55edf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtsoVBa_9SrzeWgY1M8Lz7gDcpxDdmGM4',
    appId: '1:247476803253:ios:922b5faa14bab6fa7490fc',
    messagingSenderId: '247476803253',
    projectId: 'linkup-55edf',
    databaseURL: 'https://linkup-55edf-default-rtdb.firebaseio.com/',
    storageBucket: 'linkup-55edf.firebasestorage.app',
    iosBundleId: 'com.example.linkUp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtsoVBa_9SrzeWgY1M8Lz7gDcpxDdmGM4',
    appId: '1:247476803253:ios:922b5faa14bab6fa7490fc',
    messagingSenderId: '247476803253',
    projectId: 'linkup-55edf',
    databaseURL: 'https://linkup-55edf-default-rtdb.firebaseio.com/',
    storageBucket: 'linkup-55edf.firebasestorage.app',
    iosBundleId: 'com.example.linkUp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDREWFQLkwiwRfsGjp8ZgHaGch46hdmxV8',
    appId: '1:247476803253:web:773959b03a253d4e7490fc',
    messagingSenderId: '247476803253',
    projectId: 'linkup-55edf',
    authDomain: 'linkup-55edf.firebaseapp.com',
    databaseURL: 'https://linkup-55edf-default-rtdb.firebaseio.com/',
    storageBucket: 'linkup-55edf.firebasestorage.app',
    measurementId: 'G-5Z5E9ZRJSD',
  );
}